[build]
target = "x86_64-kernel.json"

[target.x86_64-kernel.json]
runner = "bootimage runner"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
